tictactoe_games = {}

EMPTY_SYMBOL = "-"

board = [[EMPTY_SYMBOL, EMPTY_SYMBOL, EMPTY_SYMBOL],
         [EMPTY_SYMBOL, EMPTY_SYMBOL, EMPTY_SYMBOL],
         [EMPTY_SYMBOL, EMPTY_SYMBOL, EMPTY_SYMBOL]]