services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'api_log_db'
      MYSQL_USER: 'your_username'
      MYSQL_PASSWORD: 'your_password'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      -  db
    volumes:
      - ./:/app
      - ./logs:/app/logs    

volumes:
  db_data:
