version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"  # Adjust port as needed
    restart: unless-stopped
