services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: tufool
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  api:
    build: .
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8888", "--reload"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: tufool
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "8888:8888"
