version: '3.8'

services:
  web:
    build: .
    container_name: travel-time-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./routes_config.json:/app/routes_config.json
      - ./google_map_api.db:/app/google_map_api.db
    restart: unless-stopped

  # Database service for future use
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-routemonitor}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
