version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: aiops_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"   
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "${PORT:-8080}:8080"
    environment:
      FLASK_ENV: production
      DATABASE_URL: mysql+pymysql://user:password@db:3306/aiops_db
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  app_logs:
