version: "3.8"

services:
  package-conversion-api:
    build: .
    container_name: package_conversion_api
    ports:
      - "8081:8080"
    volumes:
      - ./logs:/app/logs 
      - ./data:/app/data 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

