FROM python:3.10-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .


RUN mkdir -p /app/logs /app/templates /app/static


ENV PYTHONUNBUFFERED=1
ENV GOOGLE_MAPS_API_KEY=""


EXPOSE 8000


CMD ["uvicorn", "user_interface:app", "--host", "0.0.0.0", "--port", "8000"]
